### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by sasabot** [seed-solutions/aero-ros-pkg#236]
issue to discuss correct installation procedure.
current README.md is very old.

as far as I know, the current installation procedure:
ROS dependencies
```
sudo apt-get install ros-indigo-desktop-full
sudo apt-get install ros-indigo-pr2-controller-msgs ros-indigo-move-base-msgs
sudo apt-get install ros-indigo-map-server ros-indigo-amcl ros-indigo-move-base ros-indigo-eband-local-planner
sudo apt-get install ros-indigo-moveit
sudo apt-get install ros-indigo-moveit-ros-planning-interface ros-indigo-moveit-ros-planning ros-indigo-moveit-core ros-indigo-moveit-ros-perception ros-indigo-moveit-ros-warehouse ros-indigo-moveit-kinematics
```
ROS setup
```
sudo apt-get install python-wstool python-catkin-tools
mkdir -p ~/ros/indigo
cd ~/ros/indigo
wstool init src
catkin init
catkin build
source ~/ros/indigo/devel/setup.bash
```
aero-ros-pkg install
```
cd ~/ros/indigo/src
wstool set aero-ros-pkg-prerelease https://github.com/hyaguchijsk/aero-ros-pkg-prerelease.git --git
wstool up aero-ros-pkg-prerelease
```
aero-ros-pkg-setup
```
cd aero-ros-pkg-prerelease
catkin build aero_description
soure ~/.bashrc
roscd aero_description
./setup.sh typeF  # including catkin build aero_startup
source ~/.bashrc
```
build samples
```
cd aero-ros-pkg-prerelease
catkin build aero_samples
```
run sample
```
rosrun aero_samples minimum_sample_node
```
control aero from command line
```
rostopic pub /aero_controller/command trajectory_msgs/JointTrajectory "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
joint_names:
- 'r_wrist_y_joint'
points:
- positions: [0.5]
  velocities: [0]
  accelerations: [0]
  effort: [0]
  time_from_start: {secs: 1, nsecs: 0}" 
```
```
rosservice call /aero_torso_controller  "x: 0.0
z: -200.0
coordinate: 'world:2000'"
```
writing code
see aero_samples and aero_std documentation
