### ISSUE TITLE
範囲外の動作指令を送るとコントローラノードが落ちる

### ISSUE THREAD

**Issue by YoheiKakiuchi** [seed-solutions/aero-ros-pkg#285]
オフラインで確認できて、

```
roslaunch aero_startup aero_bringup.launch
```
以下のコマンドを送ると落ちます。
```
rostopic pub /aero_controller/command trajectory_msgs/JointTrajectory "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
joint_names:
- 'r_shoulder_p_joint'
points:
- positions: [0.5]
  velocities: [0]
  accelerations: [0]
  effort: [0]
  time_from_start: {secs: 1, nsecs: 0}"
```
